### ISSUE TITLE
Block Design

### ISSUE THREAD

**Issue by fubuloubu** [GunClear/Gunero#4]
Design how blocks are published using transaction format

Requires: blockchain header information

1. Validate an incoming block (no double spends, txns all work, etc.)
2. Update header information
3. Propagate block to network

Depends on #3

**Comment by SRCoughlin** [comment]
**Protocol:**
1. Buyer shows whitelist root/proof {_SNARK_}{_QR_}
2. Buyer and seller perform financial transaction (Seller releases monetary goods)
3. Seller shows whitelist root/proof, old[][i] (Nullifier[], r[], rho[], Gunkey[]), metadata[] //serial #, etc. {_SNARK_}{_QR_}{_SECRET_}
4. Buyer verifies Gunkey, metadata (serial #, etc.) and creates new TXN and shows TXN {_SNARK_}{_QR_}
5. Seller signs and submits TXN
6. Buyer awaits and verifies TXN or views seller’s verification {_QR?_}
7. Seller releases physical goods

**TXN Structure:**
{
BuyerWhitelistRoot
BuyerWhitelistProof
SellerWhitelistRoot
SellerWhitelistProof
GunkeyWhitelistRoot
CommitmentWhitelistRoot
CommitmentWhitelistNullifierAndCommitmentProof
Nullifier[]
Commitment[] //Is the “ID”
{
r
i_Commitment[] //relative to Nullifier
rho[] //? see below
Gunkey[]
metadata[]
}
BuyerSig
SellerSig
},[AuthPK],AuthSig

**Historical Database:**
Buyer: Commitment[], r //no need to keep rest of TXN since it’s on the “chain”
Seller: old.Commitment->new.Commitment[] //no need to keep rest of TXN since it’s on the “chain”


So in total, 3 SNARKs and 3 QR reads. Plus everything shows complete verification and the minimal possible second-party trust and knowledge is required.

**Comment by SRCoughlin** [comment]
Since the SNARKs are broken up between human action stages, there will be less wait time needed. (Similar to how airports have you walk a long ways to the baggage reclaim so that you feel that you're doing something.)

**Comment by SRCoughlin** [comment]
Oh, and since there's no keys in this system I thought of this:

_Commitment = rho_ (with rho a random 2^256 variable)

_Nullifier = rho * Gunkey_

This means that you can quickly verify the truth, and can verify that there's no tampering since the above is guaranteed by the SNARK.

**Comment by SRCoughlin** [comment]
And to make sure this is written down together, **...WhitelistProof** will allow the verifier to conclude that the prover has a secret key _s_ that generates a public key _P_ that is in the SMT (Sparse Merkle Tree) given by the **...WhitelistRoot**.

CommitmentWhitelistNullifierAndCommitmentProof will allow the verifier to conclude that the prover has the public _Nullifier = rho * Gunkey_ for a secret _Commitment = rho_ that is in the SMT given by the **CommitmentWhitelistRoot** and that the secret _Gunkey_ is in the SMT given by the **GunkeyWhitelistRoot**.

**Comment by SRCoughlin** [comment]
Based on certain algebra (antagonistic/attack scenarios) we can show that it's not viable for a SNARK with false information that satisfies the SMTs to be executed in reality. (There's certain standards for computational power, such as a given number of CPU/GPU cycles, etc.)

_And the time bounds are for the maximum allowable age of the SMT roots!_

The best part of this is that the viable length of the SMTs can scale linearly with the exponential growth of all keys and transactions. So we can have short SMTs (12 levels?) to start and keep adding the length and creating new SNARKs bound to the longer SMTs as we go.

**Comment by SRCoughlin** [comment]
@fubuloubu Let me know your thoughts.

**Comment by SRCoughlin** [comment]
One more thing: if we need a way for the provenance with only partial knowledge, how about the buyer runs a SNARK that splits his/her public key _P_ into a Shamir's 2/2 separately encrypted to both the seller and to Gunclear's public key. That way Gunclear and the buyer have to cooperate to get the _P_ (which is proven actual by the SNARK).

**Comment by SRCoughlin** [comment]
Just checked what I wrote, _Nullifier = Commitment * Gunkey_ is incorrect since then an attacker can deduce Gunkey from the Nullifier with high accuracy.

Instead we can use _Commitment = rho1 * rho2 * Gunkey_ with _Nullifier = rho1 * Gunkey_ which is basically the same as ZCash with _s = rho1_ and _P = rho1 * G_ except we get to use a throwaway random variable _rho2_ which is more secure.

(And if we need to be extra safe against entropy we can use another throwaway for _Nullifier_ as well.)

**Comment by fubuloubu** [comment]
> Buyer awaits and verifies TXN or views seller’s verification {QR?}

No QR required. Buyer knows the tokenID and what the txnhash should be when the transaction is complete. It will just sit there and wait for the Seller to commit it (maybe a 10 min timeout on polling). Or, Buyer can wait for verbal confirmation from Seller and request a query in the app to verify it was received by the network.

**Comment by fubuloubu** [comment]
> Oh, and since there's no keys in this system

Yes, the same seed words that generate the account can generate an unlimited sequence of randomly generated numbers so the transactions it participated in could be recoverable potentially in case the account is moved to a different device?

**Comment by fubuloubu** [comment]
Let's follow-up on that last one in slack.

**Comment by SRCoughlin** [comment]
> Or, Buyer can wait for verbal confirmation from Seller and request a query to verify it was received by the network.

Yup, the buyer has eventual consistency so there's no need for waiting.

**Comment by fubuloubu** [comment]
> Yup, the buyer has eventual consistency so there's no need for waiting.

Well, the buyer **should** wait to leave the seller until confirming they actually submitted the nullifier lol

**Comment by fubuloubu** [comment]
Also, https://github.com/GunClear/Gunero/issues/2 might be a better spot for this discussion :)

**Comment by fubuloubu** [comment]
> 2. Buyer and seller perform financial transaction (Seller releases monetary goods)

This is external of the protocol, and may not be necessary in all circumstances (e.g. trades or gifts)

**Comment by fubuloubu** [comment]
Oh, I see what you are proposing now. A simpler protocol:

0. Buyer should validate details about the weapon at this point. An expirenced user would know this.
1. Seller provides account whitelist proof {SNARK}{QR}, and Gunkey {QR}
    Optional: Seller shows ability to sell weapon (proves ability to spend UTXO) {SNARK}
    Note: Seller can generate these proofs in the background of the app on startup or button click
2. Buyer scan's Seller's QR code, verifies gun details are accurate, and provides Account whitelist proof {SNARK}{QR}
    Note: monetary transaction would be most natural here, waiting for proof to generate
3. Seller scans Buyer's QR code, verifies info and submits TXN, which spends UTXO
4. Buyer awaits and verifies UTXO is spent and replaced with their own updated TXN
    Note: Seller would release asset here

2 QR scans, 2-3 SNARKs generated, and only steps 2 and 4 should generate significant enough wait to be awkward because proofs in step 1 could be generated prior to the process beginning.

**Comment by fubuloubu** [comment]
Inter-party Transaction and State transition function defined above

Blockchain stuff handled by: https://github.com/paritytech/substrate

**Comment by fubuloubu** [comment]
Closed per update in https://github.com/GunClear/Yellowpaper/issues/2
